- name: Dreamhost DDNS | Install script
  ansible.builtin.copy:
    src: dreamhost_ddns.sh
    dest: /usr/local/sbin/dreamhost_ddns.sh
    owner: root
    group: root
    mode: '0550'

- name: Dreamhost DDNS | Install systemd units
  ansible.builtin.template:
    src: "ddns_{{ item }}.j2"
    dest: "/etc/systemd/system/dreamhost_ddns.{{ item }}"
    owner: root
    group: root
    mode: '0640'
  loop:
    - service
    - timer

- name: Dreamhost DDNS | Enable systemd timer
  ansible.builtin.systemd:
    name: dreamhost_ddns.timer
    enabled: true
    daemon_reload: true
