- name: Load distro-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"

- name: Base configuration
  block:
    - name: Import tasks | Ansible setup
      ansible.builtin.import_tasks: ansible_setup.yml
    - name: Import tasks | Configure users
      ansible.builtin.include_tasks: users/users.yml
      loop: "{{ users | dict2items }}"
      loop_control:
        loop_var: user_item
    - name: Import tasks | OpenSSH configuration
      ansible.builtin.import_tasks: system_setup/openssh.yml
    - name: Import tasks | Firewall
      ansible.builtin.import_tasks: system_setup/firewall.yml
      when: firewalld_default_zone is defined
    - name: Import tasks | Default editor
      ansible.builtin.import_tasks: system_setup/default_editor.yml
    - name: Import tasks | Tailscale
      ansible.builtin.import_tasks: system_setup/tailscale.yml
      when: tailscale | bool
    - name: Import tasks | Scheduled reboot
      ansible.builtin.import_tasks: system_setup/scheduled_reboot.yml
      when: reboot_schedule is defined
    - name: Import tasks | Automatic updates
      ansible.builtin.import_tasks: system_setup/automatic_updates.yml
      when: automatic_updates.enabled | bool
    - name: Import tasks | ZFS
      ansible.builtin.import_tasks: system_setup/zfs.yml
      when: zfs_pool.pool_name is defined

  rescue:
    - name: Set fact if task failed
      ansible.builtin.set_fact:
        task_failed: true
