
- name: Base configuration
  block:
  # set up the ansible environment
    - name: Import tasks | Ansible setup
      ansible.builtin.import_tasks: ansible_setup.yml

    # # install software
    # - name: Import tasks | Packages utilities
    #   ansible.builtin.import_tasks: software/packages_utilities.yml

    # # User configuration
    # - name: Include tasks | Additional users
    #   ansible.builtin.include_tasks: users/additional_users.yml
    #   with_dict: "{{ additional_users }}"
    #   when: additional_users is defined

    # # perform remaining tasks:
    # - name: Import tasks | Automatic updates
    #   ansible.builtin.import_tasks: system_setup/automatic_updates.yml
    #   when: automatic_updates | bool
    # - name: Import tasks | OpenSSH configuration
    #   ansible.builtin.import_tasks: system_setup/openssh.yml
    #   when: sshd | bool
    # - name: Import tasks | Tailscale
    #   ansible.builtin.import_tasks: system_setup/tailscale.yml
    #   when: tailscale | bool
    # - name: Import tasks | Scheduled reboot
    #   ansible.builtin.import_tasks: system_setup/scheduled_reboot.yml
    #   when: reboot_schedule is defined

  rescue:
    - name: Set fact if task failed
      ansible.builtin.set_fact:
        task_failed: true
