- name: Load distro-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"

- name: Base configuration
  block:
  # set up the ansible environment
    - name: Import tasks | Ansible setup
      ansible.builtin.import_tasks: ansible_setup.yml

    # # User configuration
    # - name: Include tasks | Additional users
    #   ansible.builtin.include_tasks: users/additional_users.yml
    #   with_dict: "{{ additional_users }}"
    #   when: additional_users is defined

    - name: Import tasks | OpenSSH configuration
      ansible.builtin.import_tasks: system_setup/openssh.yml
    - name: Import tasks | Tailscale
      ansible.builtin.import_tasks: system_setup/tailscale.yml
      when: tailscale | bool
    - name: Import tasks | Scheduled reboot
      ansible.builtin.import_tasks: system_setup/scheduled_reboot.yml
      when: reboot_schedule is defined

  rescue:
    - name: Set fact if task failed
      ansible.builtin.set_fact:
        task_failed: true
