version: "3.5"
services:
  nginx:
    container_name: nginx
    image: docker.io/library/nginx:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
