services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    volumes:
      - ${DATADIR}/config/gluetun:/gluetun:z
    ports:
      - 8112:8112
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER={{ vpn_client_username }}
      - OPENVPN_PASSWORD={{ vpn_client_password }}
      - SERVER_REGIONS=US Seattle
      - TZ=${TZ} # timezone, defined in .env

  deluge:
    container_name: deluge
    image: lscr.io/linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:gluetun # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${MEDIADIR}/downloads:/downloads:z # downloads folder
      - ${DATADIR}/config/deluge:/config:z # config files
    security_opt:
      - label=level:s0:c196,c913

  jackett:
    container_name: jackett
    image: lscr.io/linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIADIR}/downloads/torrent-blackhole:/downloads:z # place where to put .torrent files for manual download
      - ${DATADIR}/config/jackett:/config:z # config files

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATADIR}/config/sonarr:/config:z # config files
      - ${MEDIADIR}/tv:/tv:z # tv shows folder
      - ${MEDIADIR}/downloads:/downloads:z # download folder

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATADIR}/config/radarr:/config:z # config files
      - ${MEDIADIR}/movies:/movies:z # movies folder
      - ${MEDIADIR}/downloads:/downloads:z # download folder

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${DATADIR}/config/prowlarr:/config:z # config files
  
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATADIR}/config/tautulli:/config:z
    network_mode: host
    ports:
      - 8181:8181
    restart: unless-stopped

  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    network_mode: host
    volumes:
      - ${DATADIR}/config/plex/db:/config:z # plex database
      - ${DATADIR}/config/plex/transcode:/transcode:z # temp transcoded files
      - ${MEDIADIR}/tv:/tv:z # media library
      - ${MEDIADIR}/movies:/movies:z # media library

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${DATADIR}/config/bazarr:/config:z # config files
      - ${MEDIADIR}/movies:/movies:z # movies folder
      - ${MEDIADIR}/tv:/tv:z # tv shows folder

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${DATADIR}/config/homeassitant:/config:z
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  scrypted:
    container_name: scrypted
    restart: unless-stopped
    network_mode: host
    image: koush/scrypted
    volumes:
      - ${DATADIR}/config/scrypted:/server/volume:z
