- name: System setup | openssh | copy borcean.conf to config.d
  tags: openssh,ssh,system,settings
  ansible.builtin.copy:
    src: system_setup/sshd_config_borcean
    dest: /etc/ssh/sshd_config.d/100-borcean.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart_SSHD
